package main

import (	
	"os"
	"net/url"
	"github.com/zserge/webview"
)

const VIRTUALWROOT = "res"

func main() {
	// get index file generated by command "go-bindata -o assets.go res/..." 
	fname := VIRTUALWROOT+string(os.PathSeparator)+"index.html"
	data, err := Asset(fname)
	if err != nil {
		panic("page not found: " + fname)
		os.Exit(1)
	}
	w := webview.New(webview.Settings{
		Title: "RhumDapp",
		URL:   "data:text/html," + url.PathEscape(string(data)),
	})
	defer w.Exit()
	w.Run()	
}
